spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml
  redis:
    # Redis服务器地址
    #    host: 175.178.183.32
    host: 10.0.0.41
    # Redis数据库索引（默认为0）
    database: 13
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000ms

logging:
  level:
    root: info
    com:
      obeast:
        debug

gateway:
  ignoreUrls:
    - "/doc.html"
    - "/v3/api-docs/swagger-config"
    - "/swagger-resources/**"
    - "/swagger/**"
    - "/swagger-ui/**"
    - "/**/**.js"
    - "/**/**.css"
    - "/**/**.png"
    - "/**/**.ico"
