
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bendan?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: mysql1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  redis:
    host: 175.178.183.32 # Redis服务器地址
    database: 13 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

  rabbitmq:
    host: 175.178.183.32
    port: 5672
    username: guest
    password: guest
    virtual-host: /plant
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        concurrency: 5 # 消费端最小并发数
        max-concurrency: 10 # 消费端最大并发数
        prefetch: 5 # 一次请求中预处理的消息数量
    cache:
      channel:
        size: 50 # 缓存的channel数量

netty:
  host: 127.0.0.1
  port: 9991

logging:
  level:
    root: info
    com:
      obeast:
        debug


#-----自定义配置
security:
  resources:
    ignore:
      urls:
        - "/v3/api-docs/**"
        - "/swagger-ui/**"
        - "/swagger-ui.html/**"
        - "/swagger-resources/**"
        - "/favicon.ico"
        - "/oauth2/token"
        - "/sysUser/login"


# swagger 配置
swagger:
  enabled: true
  title: bendan Swagger API
  gateway: http://${GATEWAY_HOST:127.0.0.1}:${GATEWAY-PORT:8888}
  token-url: ${swagger.gateway}/auth/oauth2/token
  scope: message.read
  services:
    bendan-admin: admin
    bendan-chat: chat