spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bendan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: mysql1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


#---en delete
logging:
  level:
    root: warn
    com.Irm: info
  file:
    name: log/BenDan-pro.log

server:
  port: 8080