spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bendan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: mysql1234
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    # Redis服务器地址
    host: 175.178.183.32
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000ms


logging:
  level:
    com:
      obeast:
        debug


security:
  resources:
    ignore:
      urls:
        - "/v3/api-docs/**"
        - "/swagger-ui/**"
        - "/swagger-ui.html"
        - "/swagger-resources/**"
        - "/swagger-config/**"
        - "/favicon.ico"
        - "/oauth2/token/**"
