spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bendan_oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: mysql1234
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    # Redis服务器地址
    host: 175.178.183.32
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000ms

logging:
  level:
    root: info
    com:
      obeast:
        debug

