spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bendan?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: mysql1234
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500



  redis:
    # Redis服务器地址
#    host: 10.0.0.41
    host: 175.178.183.32
    # Redis数据库索引（默认为0）
    database: 13
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000ms


mybatis-plus:
  #扫描包并打印日志
  #  mapper-locations: classpath:/mapper/admin/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      # 逻辑已删除值(默认为 2)
      logic-delete-value: 2
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

#
##指定接口包扫描
#springdoc.packagesToScan: com.obeast.bendan.controller
##或者指定访问接口路径扫描
##springdoc.pathsToMatch=/hs/**, /hsType/**
#
## swagger-ui custom path
#springdoc.swagger-ui.path: /swagger-ui.html
#


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    com:
      obeast:
        debug

#-----自定义配置
security:
  resources:
    ignore:
      urls:
        - "/v3/api-docs/**"
        - "/swagger-ui/**"
        - "/swagger-ui.html/**"
        - "/swagger-resources/**"
        - "/favicon.ico"
        - "/oauth2/token"
        - "/sysUser/login"


# swagger 配置
swagger:
  enabled: true
  title: bendan Swagger API
  gateway: http://${GATEWAY_HOST:127.0.0.1}:${GATEWAY-PORT:8888}
  token-url: ${swagger.gateway}/auth/oauth2/token
  scope: message.read
  services:
    agri-iot-admin: admin